### ISSUE TITLE
Why the number is 1 in your code?

### ISSUE THREAD

**Issue by roxanasoto** [XuyangBai/PPF-FoldNet#9]
Hi, thanks for code! 
I have a question: why the number of patch is 1 in your code? In the original paper the number of patch es 2048 or 5k, but in training.py you defined in the líne 21 like 1?
Thanks!

**Comment by XuyangBai** [comment]
I might use a misleading variable name during the implementation. To be specific, I use 1 point cloud pairs, select 32 corresponding point cloud patches, each patch contains 1024 points (from the paper the authors use 2048). I forget why I use 1024 instead (maybe due to memory limitation, or the performance is similar) 

https://github.com/XuyangBai/PPF-FoldNet/blob/63af940632ad2350141e332314aab99f41766378/train.py#L21-L23
